// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPREQFVbsBWeIY5iYVzlK05QtvEBIMmFE',
    appId: '1:1089825241516:web:2ad75732aea2ef3ac66209',
    messagingSenderId: '1089825241516',
    projectId: 'tripflow-3bef3',
    authDomain: 'tripflow-3bef3.firebaseapp.com',
    storageBucket: 'tripflow-3bef3.firebasestorage.app',
    measurementId: 'G-L3BQGKVP17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARzIeOZSXd9r0Wt74B2KRAv8WzEkfOSR0',
    appId: '1:1089825241516:android:8fd8ebc82ef0797ac66209',
    messagingSenderId: '1089825241516',
    projectId: 'tripflow-3bef3',
    storageBucket: 'tripflow-3bef3.firebasestorage.app',
  );
}
